# docker-compose.yml
version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - memcached
    environment:
      - DJANGO_SETTINGS_MODULE=pricing_api.settings  # Adjust if necessary

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"